"""In-app notifications generated by marketplace and chat events."""

from django.db import models


class Notification(models.Model):
    """A single notification addressed to a user."""

    recipient = models.ForeignKey(
        'users.User', on_delete=models.CASCADE, related_name='notifications'
    )
    actor = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='+',
    )
    verb = models.CharField(max_length=64)
    target_type = models.CharField(max_length=50, blank=True)
    target_id = models.PositiveBigIntegerField(null=True, blank=True)
    data = models.JSONField(default=dict, blank=True)
    is_read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['recipient', 'is_read']),
            models.Index(fields=['recipient', '-created_at']),
        ]

    def __str__(self):
        return f'Notification {self.pk} for {self.recipient_id} ({self.verb})'
