# Generated by Django 6.1.1 on 2026-09-06 10:51

import django.db.models.deletion
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                (
                    'delivery_time_days',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('is_remote', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                (
                    'cover_image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='listings/',
                        validators=[apps.core.validators.validate_uploaded_image],
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='listings',
                        to='listings.category',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listings',
                        to='profiles.profile',
                    ),
                ),
                (
                    'skills',
                    models.ManyToManyField(
                        blank=True, related_name='listings', to='profiles.skill'
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('message', models.TextField(blank=True, max_length=500)),
                (
                    'proposed_price',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('rejected', 'Rejected'),
                            ('withdrawn', 'Withdrawn'),
                        ],
                        default='pending',
                        max_length=12,
                    ),
                ),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'applicant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to='profiles.profile',
                    ),
                ),
                (
                    'listing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='applications',
                        to='listings.listing',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(
                fields=['category', 'is_active'], name='listings_li_categor_22a522_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(
                fields=['-created_at'], name='listings_li_created_92fa22_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'pending')),
                fields=('listing', 'applicant'),
                name='unique_pending_application',
            ),
        ),
    ]
