# Generated by Django 6.1.1 on 2026-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderation_status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('pending', 'Pending approval'),
                    ('published', 'Published'),
                    ('rejected', 'Rejected'),
                    ('suspended', 'Suspended'),
                    ('archived', 'Archived'),
                ],
                default='published',
                help_text='Lifecycle state tracked by the moderation workflow.',
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(
                fields=['moderation_status'], name='listings_li_moderat_cdd1ec_idx'
            ),
        ),
    ]
