# Generated by Django 6.1.1 on 2026-09-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='avatars/',
                        validators=[apps.profiles.models.validate_avatar],
                    ),
                ),
                ('university', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('is_student', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_verified_student', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'skills',
                    models.ManyToManyField(
                        blank=True, related_name='profiles', to='profiles.skill'
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['university'], name='profiles_pr_univers_2be684_idx'
                    ),
                    models.Index(
                        fields=['is_searchable', 'is_verified_student'],
                        name='profiles_pr_is_sear_a85180_idx',
                    ),
                ],
            },
        ),
    ]
