# Generated by Django 6.1.1 on 2026-09-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user verified ownership of their email address.',
            ),
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('email_verification', 'Email verification'),
                            ('password_reset', 'Password reset'),
                        ],
                        max_length=32,
                    ),
                ),
                ('hashed_code', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='one_time_passwords',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['user', 'purpose', 'is_used'],
                        name='users_oneti_user_id_8cab4d_idx',
                    )
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_used', False)),
                        fields=('user', 'purpose', 'is_used'),
                        name='unique_active_otp_per_purpose',
                    )
                ],
            },
        ),
    ]
