# Generated by Django 6.1.1 on 2026-09-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('note', models.TextField(blank=True, max_length=500)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending_payment', 'Pending payment'),
                            ('paid', 'Paid'),
                            ('in_progress', 'In progress'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('refunded', 'Refunded'),
                        ],
                        default='pending_payment',
                        max_length=20,
                    ),
                ),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'application',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order',
                        to='listings.application',
                    ),
                ),
                (
                    'buyer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders_as_buyer',
                        to='profiles.profile',
                    ),
                ),
                (
                    'listing',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='orders',
                        to='listings.listing',
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders_as_provider',
                        to='profiles.profile',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('paid', 'Paid'),
                            ('refunded', 'Refunded'),
                            ('failed', 'Failed'),
                        ],
                        default='created',
                        max_length=10,
                    ),
                ),
                ('gateway', models.CharField(default='stripe', max_length=20)),
                ('gateway_session_id', models.CharField(blank=True, max_length=255)),
                ('gateway_charge_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payment',
                        to='orders.order',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['buyer', 'status'], name='orders_orde_buyer_i_4389c9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['provider', 'status'], name='orders_orde_provide_856163_idx'
            ),
        ),
    ]
