# Generated by Django 6.1.1 on 2026-09-07 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'target_type',
                    models.CharField(
                        choices=[
                            ('user', 'User'),
                            ('listing', 'Listing'),
                            ('message', 'Message'),
                            ('review', 'Review'),
                        ],
                        max_length=16,
                    ),
                ),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('reviewing', 'Reviewing'),
                            ('resolved', 'Resolved'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending',
                        max_length=12,
                    ),
                ),
                ('admin_notes', models.TextField(blank=True, max_length=2000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'reporter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reports_made',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reports_reviewed',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'moderation_report',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['status'], name='moderation__status_3fc7e7_idx'
                    ),
                    models.Index(
                        fields=['target_type', 'target_id'],
                        name='moderation__target__dc17d8_idx',
                    ),
                    models.Index(
                        fields=['reporter'], name='moderation__reporte_6f6e5c_idx'
                    ),
                ],
            },
        ),
    ]
